# version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: asimsaikhu/paro:saikhugitio
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGETPLATFORM: linux/amd64
    ports:
      - 8080:8080
    volumes:
      - .:/srv/jekyll
